delete from visits;
delete from doctors;
delete from patients;
insert into patients values (123, 'Yakov');
insert into patients values (124, 'Rivka');
insert into patients values (125, 'Gabriel');
insert into patients values (126, 'Dalia');
insert into doctors values ('shlomi@hospital.com', 'Dr Shlomi');
insert into doctors values ('izhak@hospital.com', 'Dr Izhak');
insert into doctors values ('shira@hospital.com', 'Dr Shira');
insert into doctors values ('rozi@hospital.com', 'Dr Rozi');
insert into visits (doctor_name, patient_name, date) values ('Dr Shlomi', 'Yakov', '2023-10-01');
insert into visits (doctor_name, patient_name, date) values ('Dr Izhak', 'Rivka', '2023-10-02');
insert into visits (doctor_name, patient_name, date) values ('Dr Shira', 'Gabriel', '2023-10-03');
insert into visits (doctor_name, patient_name, date) values ('Dr Rozi', 'Dalia', '2023-10-04');
